"""
Copyright (C) 2013, 2014, 2015 2016 Digital Freedom Foundation

  GNUKhata is Free Software; you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation; either version 3 of
  the License, or (at your option) any later version.

  GNUKhata is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public
  icense along with GNUKhata (COPYING); if not, write to the
  Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
  Boston, MA  02110-1301  USA59 Temple Place, Suite 330,


Contributors:
"Survesh" <123survesh@gmail.com>
"Sai Karthik"<kskarthik@disroot.org>

"""
from pyramid.response import Response
from gkcore.models.meta import gk_api

# Spreadsheet libraries
import openpyxl
from openpyxl.styles import Font, Alignment

# from io import BytesIO
import io


def generate_spreadsheet(self):
    """
    This function returns a spreadsheet form of List of Accounts Report.
    The spreadsheet in XLSX format is generated by the backend and sent in base64 encoded format.
    It is decoded and returned along with mime information.
    """

    try:
        header = {"gktoken": self.request.headers["gktoken"]}
        # subreq = Request.blank("/accounts", headers=header)
        # result = json.loads(self.request.invoke_subrequest(subreq).text)["gkresult"]
        result = gk_api("/accounts", header, self.request)["gkresult"]
        fystart = str(self.request.params["fystart"])
        fyend = str(self.request.params["fyend"])
        orgname = str(self.request.params["orgname"])
        # A workbook is opened.
        accountwb = openpyxl.Workbook()
        # The new sheet is the active sheet as no other sheet exists. It is set as value of variable - sheet.
        sheet = accountwb.active
        # Title of the sheet and width of columns are set.
        sheet.title = "List of Accounts"
        sheet.column_dimensions["A"].width = 8
        sheet.column_dimensions["B"].width = 18
        sheet.column_dimensions["C"].width = 14
        sheet.column_dimensions["D"].width = 24
        sheet.column_dimensions["E"].width = 24

        # Cells of first two rows are merged to display organisation details properly.
        sheet.merge_cells("A1:G2")
        # Font and Alignment of cells are set. Each cell can be identified using the cell index - column name and row number.
        sheet["A1"].font = Font(name="Liberation Serif", size="16", bold=True)
        sheet["A1"].alignment = Alignment(horizontal="center", vertical="center")
        # Organisation name and financial year are displayed.
        sheet["A1"] = orgname + " (FY: " + fystart + " to " + fyend + ")"
        sheet.merge_cells("A3:G3")
        sheet["A3"].font = Font(name="Liberation Serif", size="14", bold=True)
        sheet["A3"].alignment = Alignment(horizontal="center", vertical="center")
        sheet["A3"] = "List of Accounts"
        sheet.merge_cells("A3:G3")
        sheet["A4"] = "Sr. No."
        sheet["B4"] = "Account Name"
        sheet["C4"] = "Group Name"
        sheet["D4"] = "Sub-group Name"
        sheet["E4"] = "Default A/C for"
        titlerow = sheet.row_dimensions[4]
        titlerow.font = Font(name="Liberation Serif", size=12, bold=True)
        row = 5
        srno = 1
        for accrow in result:
            sheet["A" + str(row)] = srno
            sheet["A" + str(row)].alignment = Alignment(horizontal="left")
            sheet["A" + str(row)].font = Font(
                name="Liberation Serif", size="12", bold=False
            )
            sheet["B" + str(row)] = accrow["accountname"]
            sheet["B" + str(row)].font = Font(
                name="Liberation Serif", size="12", bold=False
            )
            sheet["C" + str(row)] = accrow["groupname"]
            sheet["C" + str(row)].font = Font(
                name="Liberation Serif", size="12", bold=False
            )
            sheet["D" + str(row)] = accrow["subgroupname"]
            sheet["D" + str(row)].font = Font(
                name="Liberation Serif", size="12", bold=False
            )
            sheet["E" + str(row)] = accrow["defaultflag"]
            sheet["E" + str(row)].font = Font(
                name="Liberation Serif", size="12", bold=False
            )
            row = row + 1
            srno += 1
        output = io.BytesIO()
        accountwb.save(output)
        contents = output.getvalue()
        output.close()
        headerList = {
            "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "Content-Length": len(contents),
            "Content-Disposition": "attachment; filename=report.xlsx",
            "X-Content-Type-Options": "nosniff",
            "Accept-Charset": "UTF-8",
            "Set-Cookie": "fileDownload=true; path=/[;HttpOnly]",
        }
        return Response(contents, headerlist=list(headerList.items()))
    except:
        return {"gkstatus": 3}
