"""
Copyright (C) 2013, 2014, 2015, 2016 Digital Freedom Foundation
Copyright (C) 2017, 2018, 2019, 2020, 2021 Digital Freedom Foundation & Accion Labs Pvt. Ltd.
  This file is part of GNUKhata:A modular,robust and Free Accounting System.

  GNUKhata is Free Software; you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation; either version 3 of
  the License, or (at your option) any later version.

  GNUKhata is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public
  License along with GNUKhata (COPYING); if not, write to the
  Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
  Boston, MA  02110-1301  USA59 Temple Place, Suite 330,


Contributors:
"Survesh" <123survesh@gmail.com>
"Sai Karthik"<kskarthik@disroot.org>

"""
from pyramid.response import Response

# from pyramid.request import Request
from datetime import datetime

# Spreadsheet libraries
import openpyxl
from openpyxl.styles import Font, Alignment

# from io import BytesIO
import io

from gkcore.models.meta import gk_api


def print_cash_flow(self):
    """
    This function returns a spreadsheet form of Cash Flow Account Report.
    The spreadsheet in XLSX format is generated by the backend and sent in base64 encoded format.
    It is decoded and returned along with mime information.

    params
    ======
    from
    to
    fystart
    fyend
    orgname
    orgtype
    """
    try:
        calculatefrom = self.request.params["from"]
        calculateto = self.request.params["to"]
        financialstart = self.request.params["fystart"]
        fyend = str(self.request.params["fyend"])
        orgname = self.request.params["orgname"]
        orgtype = self.request.params["orgtype"]
        header = {"gktoken": self.request.headers["gktoken"]}
        result = gk_api(
            f"/reports/cash-flow?calculateto={calculateto}&financialstart={financialstart}&calculatefrom={calculatefrom}",
            header,
            self.request,
        )
        receipt = result["gkresult"]["rcgkresult"]
        payment = result["gkresult"]["pygkresult"]
        fystart = datetime.strptime(
            self.request.params["fystart"], "%Y-%m-%d"
        ).strftime("%d-%m-%Y")
        orgname = str(self.request.params["orgname"])
        calculateto = calculateto[8:10] + calculateto[4:8] + calculateto[0:4]
        calculatefrom = calculatefrom[8:10] + calculatefrom[4:8] + calculatefrom[0:4]
        # A workbook is opened.
        cashwb = openpyxl.Workbook()
        # The new sheet is the active sheet as no other sheet exists. It is set as value of variable - sheet.
        sheet = cashwb.active
        # Title of the sheet and width of columns are set.
        # sheet.title = "List of Accounts"
        sheet.column_dimensions["A"].width = 4
        sheet.column_dimensions["B"].width = 32
        sheet.column_dimensions["C"].width = 13
        sheet.column_dimensions["D"].width = 4
        sheet.column_dimensions["E"].width = 32
        sheet.column_dimensions["F"].width = 13
        # Cells of first two rows are merged to display organisation details properly.
        sheet.merge_cells("A1:F2")
        # Font and Alignment of cells are set. Each cell can be identified using the cell index - column name and row number.
        sheet["A1"].font = Font(name="Liberation Serif", size="16", bold=True)
        sheet["A1"].alignment = Alignment(horizontal="center", vertical="center")
        # Organisation name and financial year are displayed.
        sheet["A1"] = orgname + " (FY: " + fystart + " to " + fyend + ")"
        sheet.merge_cells("A3:F3")
        sheet["A3"].font = Font(name="Liberation Serif", size="14", bold=True)
        sheet["A3"].alignment = Alignment(horizontal="center", vertical="center")
        # Cells of first two rows are merged to display organisation details properly.
        sheet.merge_cells("A1:F2")
        # Font and Alignment of cells are set. Each cell can be identified using the cell index - column name and row number.
        sheet["A1"].font = Font(name="Liberation Serif", size="16", bold=True)
        sheet["A1"].alignment = Alignment(horizontal="center", vertical="center")
        # Organisation name and financial year are displayed.
        sheet["A1"] = orgname + " (FY: " + fystart + " to " + fyend + ")"
        sheet.merge_cells("A3:F3")
        sheet["A3"].font = Font(name="Liberation Serif", size="14", bold=True)
        sheet["A3"].alignment = Alignment(horizontal="center", vertical="center")
        if orgtype == "Profit Making":
            sheet.title = "Cash Flow Statement"
            sheet["A3"] = (
                "Cash Flow Statement (" + calculatefrom + " to " + calculateto + ")"
            )
        if orgtype == "Not For Profit":
            sheet.title = "Receipt & Payment Account"
            sheet["A3"] = (
                "Receipt & Payment Account ("
                + calculatefrom
                + " to "
                + calculateto
                + ")"
            )
        sheet.merge_cells("A3:F3")
        sheet["B4"] = "Particulars"
        sheet["C4"] = "Amount"
        sheet["E4"] = "Particulars"
        sheet["F4"] = "Amount"
        titlerow = sheet.row_dimensions[4]
        titlerow.font = Font(name="Liberation Serif", size=12, bold=True)
        sheet["C4"].alignment = Alignment(horizontal="right")
        sheet["F4"].alignment = Alignment(horizontal="right")
        sheet["C4"].font = Font(name="Liberation Serif", size=12, bold=True)
        sheet["F4"].font = Font(name="Liberation Serif", size=12, bold=True)
        row = 5
        for account in receipt:
            sheet["A" + str(row)] = account["toby"]
            sheet["A" + str(row)].alignment = Alignment(horizontal="left")
            sheet["A" + str(row)].font = Font(
                name="Liberation Serif", size="12", bold=False
            )
            if account["toby"] != "" and account["particulars"] != "Opening balance":
                sheet["B" + str(row)] = account["particulars"]
                sheet["B" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
                sheet["C" + str(row)] = ""
                sheet["C" + str(row)] = float("%.2f" % float(account["amount"]))
                sheet["C" + str(row)].number_format = "0.00"
                sheet["C" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
            else:
                sheet["B" + str(row)] = account["particulars"]
                sheet["B" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
                if account["amount"] != "." and account["amount"] != "":
                    sheet["C" + str(row)] = float("%.2f" % float(account["amount"]))
                    sheet["C" + str(row)].number_format = "0.00"
                    sheet["C" + str(row)].font = Font(
                        name="Liberation Serif", size="12", bold=False
                    )
            row += 1
        row = 5
        for account in payment:
            sheet["D" + str(row)] = account["toby"]
            sheet["D" + str(row)].alignment = Alignment(horizontal="left")
            sheet["D" + str(row)].font = Font(
                name="Liberation Serif", size="12", bold=False
            )
            if account["toby"] != "" and account["particulars"] != "Closing balance":
                sheet["E" + str(row)] = account["particulars"]
                sheet["E" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
                sheet["F" + str(row)] = ""
                sheet["F" + str(row)] = float("%.2f" % float(account["amount"]))
                sheet["F" + str(row)].number_format = "0.00"
                sheet["F" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
            else:
                sheet["E" + str(row)] = account["particulars"]
                sheet["E" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
                if account["amount"] != "." and account["amount"] != "":
                    sheet["F" + str(row)] = float("%.2f" % float(account["amount"]))
                    sheet["F" + str(row)].number_format = "0.00"
                    sheet["F" + str(row)].font = Font(
                        name="Liberation Serif", size="12", bold=False
                    )
            row += 1
        output = io.BytesIO()
        cashwb.save(output)
        contents = output.getvalue()
        output.close()
        headerList = {
            "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "Content-Length": len(contents),
            "Content-Disposition": "attachment; filename=report.xlsx",
            "X-Content-Type-Options": "nosniff",
            "Set-Cookie": "fileDownload=true; path=/ [;HttpOnly]",
        }
        # headerList = {'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' ,'Content-Length': len(contents),'Content-Disposition': 'attachment; filename=report.xlsx', 'Set-Cookie':'fileDownload=true; path=/' }
        return Response(contents, headerlist=list(headerList.items()))
        # return Response(reportxslx, headerlist=list(headerList.items()))
    except Exception as e:
        return {"gkstatus": 3, "error": e}
