"""
Copyright (C) 2013, 2014, 2015, 2016 Digital Freedom Foundation
Copyright (C) 2017, 2018, 2019, 2020 Digital Freedom Foundation & Accion Labs Pvt. Ltd.
  This file is part of GNUKhata:A modular,robust and Free Accounting System.

  GNUKhata is Free Software; you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation; either version 3 of
  the License, or (at your option) any later version.

  GNUKhata is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public
  License along with GNUKhata (COPYING); if not, write to the
  Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
  Boston, MA  02110-1301  USA59 Temple Place, Suite 330,


Contributors:
"Survesh" <123survesh@gmail.com>
"Sai Karthik"<kskarthik@disroot.org>

"""

# from gkcore import eng, enumdict
# from gkcore.views.api_login import authCheck
# from gkcore.models.gkdb import (
#     organisation,
#     unitofmeasurement,
#     product,
#     goprod,
#     stock,
#     categorysubcategories,
# )
# from sqlalchemy.sql import select
# from sqlalchemy.engine.base import Connection
# from sqlalchemy import and_, exc, func
from pyramid.request import Request
from pyramid.response import Response

# from pyramid.view import view_defaults, view_config
# import gkcore
# from gkcore.views.api_reports import getBalanceSheet
# from gkcore.views.api_invoice import getInvoiceList
from datetime import datetime

# from gkcore.views.api_user import getUserRole
import json

# Spreadsheet libraries
import openpyxl
from openpyxl.styles import Font, Alignment
from openpyxl.styles.colors import Color

RED = Color(rgb="FF0000")


# from io import BytesIO
import io


def print_trial_balance(self):
    """
    This function returns a spreadsheet form of Trial Balance Report.
    The spreadsheet in XLSX format is generated by the frontendend.

    params
    ======
    orgname
    fystart
    fyend
    calculateto
    trialbalancetype

    """
    try:
        header = {"gktoken": self.request.headers["gktoken"]}
        orgname = self.request.params["orgname"]
        financialstart = self.request.params["fystart"]
        fyend = str(self.request.params["fyend"])
        startdate = self.request.params["fystart"]
        calculateto = self.request.params["calculateto"]
        trialbalancetype = int(self.request.params["trialbalancetype"])
        result = {}
        if trialbalancetype == 1:
            subreq = Request.blank(
                "/reports/trial-balance/net?&calculateto=%s&financialstart=%s"
                % (calculateto, financialstart),
                headers=header,
            )
            result = self.request.invoke_subrequest(subreq)
        elif trialbalancetype == 2:
            subreq = Request.blank(
                "/reports/trial-balance/gross?calculateto=%s&financialstart=%s"
                % (calculateto, financialstart),
                headers=header,
            )
            result = self.request.invoke_subrequest(subreq)
        elif trialbalancetype == 3:
            subreq = Request.blank(
                "/reports/trial-balance/extended?calculateto=%s&financialstart=%s"
                % (calculateto, financialstart),
                headers=header,
            )
            result = self.request.invoke_subrequest(subreq)
        records = json.loads(result.text)["gkresult"]
        trialbalancewb = openpyxl.Workbook()
        sheet = trialbalancewb.active
        sheet.title = "Trial Balance of %s" % (str(orgname))
        # Condition for Net Trial Balance
        if trialbalancetype == 1:
            sheet.column_dimensions["A"].width = 8
            sheet.column_dimensions["B"].width = 20
            sheet.column_dimensions["C"].width = 14
            sheet.column_dimensions["D"].width = 16
            sheet.column_dimensions["E"].width = 22
            # Cells of first two rows are merged to display organisation details properly.
            sheet.merge_cells("A1:E2")
            # Name and Financial Year of organisation is fetched to be displayed on the first row.
            sheet["A1"].font = Font(name="Liberation Serif", size="16", bold=True)
            sheet["A1"].alignment = Alignment(horizontal="center", vertical="center")
            # Organisation name and financial year are displayed.
            sheet["A1"] = (
                orgname
                + " (From: "
                + datetime.strptime(str(financialstart), "%Y-%m-%d").strftime(
                    "%d-%m-%Y"
                )
                + " To: "
                + fyend
                + ")"
            )
            sheet.merge_cells("A3:F3")
            sheet["A3"].font = Font(name="Liberation Serif", size="14", bold=True)
            sheet["A3"].alignment = Alignment(horizontal="center", vertical="center")
            sheet["A3"] = "Net Trial Balance for the period from %s to %s" % (
                datetime.strptime(str(startdate), "%Y-%m-%d").strftime("%d-%m-%Y"),
                datetime.strptime(str(calculateto), "%Y-%m-%d").strftime("%d-%m-%Y"),
            )
            sheet["A4"] = "Sr. No."
            sheet["B4"] = "Account Name"
            sheet["C4"] = "Debit"
            sheet["D4"] = "Credit"
            sheet["E4"] = "Group Name"
            titlerow = sheet.row_dimensions[4]
            titlerow.font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["C4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["D4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["E4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["c4"].alignment = Alignment(horizontal="right")
            sheet["D4"].alignment = Alignment(horizontal="right")
            sheet["E4"].alignment = Alignment(horizontal="center")
            row = 5
            for record in records:
                sheet["A" + str(row)] = record["srno"]
                sheet["A" + str(row)].alignment = Alignment(horizontal="left")
                sheet["A" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
                sheet["B" + str(row)] = record["accountname"]
                sheet["B" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
                if record["advflag"] == 1:
                    if record["Dr"] != "":
                        sheet["C" + str(row)] = float("%.2f" % float(record["Dr"]))
                        sheet["C" + str(row)].number_format = "0.00"
                        sheet["C" + str(row)].alignment = Alignment(horizontal="right")
                        sheet["C" + str(row)].font = Font(
                            name="Liberation Serif", size="12", bold=True, color=RED
                        )
                    if record["Cr"] != "":
                        sheet["D" + str(row)] = float("%.2f" % float(record["Cr"]))
                        sheet["D" + str(row)].number_format = "0.00"
                    sheet["D" + str(row)].alignment = Alignment(horizontal="right")
                    sheet["D" + str(row)].font = Font(
                        name="Liberation Serif", size="12", bold=True, color=RED
                    )
                else:
                    if record["Dr"] != "":
                        sheet["C" + str(row)] = float("%.2f" % float(record["Dr"]))
                        sheet["C" + str(row)].number_format = "0.00"
                    sheet["C" + str(row)].alignment = Alignment(horizontal="right")
                    sheet["C" + str(row)].font = Font(
                        name="Liberation Serif", size="12", bold=False
                    )
                    if record["Cr"] != "":
                        sheet["D" + str(row)] = float("%.2f" % float(record["Cr"]))
                        sheet["D" + str(row)].number_format = "0.00"
                    sheet["D" + str(row)].alignment = Alignment(horizontal="right")
                    sheet["D" + str(row)].font = Font(
                        name="Liberation Serif", size="12", bold=False
                    )
                sheet["E" + str(row)] = record["groupname"]
                sheet["E" + str(row)].alignment = Alignment(horizontal="center")
                sheet["E" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
                row = row + 1
        # Condition for Gross Trial Balance
        elif trialbalancetype == 2:
            sheet.column_dimensions["A"].width = 8
            sheet.column_dimensions["B"].width = 20
            sheet.column_dimensions["C"].width = 18
            sheet.column_dimensions["D"].width = 18
            sheet.column_dimensions["E"].width = 20
            sheet.column_dimensions["F"].width = 20
            sheet.column_dimensions["G"].width = 20
            # Cells of first two rows are merged to display organisation details properly.
            sheet.merge_cells("A1:G2")
            # Name and Financial Year of organisation is fetched to be displayed on the first row.
            sheet["A1"].font = Font(name="Liberation Serif", size="16", bold=True)
            sheet["A1"].alignment = Alignment(horizontal="center", vertical="center")
            # Organisation name and financial year are displayed.
            sheet["A1"] = (
                orgname
                + " (FY: "
                + datetime.strptime(str(financialstart), "%Y-%m-%d").strftime(
                    "%d-%m-%Y"
                )
                + " to "
                + fyend
                + ")"
            )
            sheet.merge_cells("A3:G3")
            sheet["A3"].font = Font(name="Liberation Serif", size="14", bold=True)
            sheet["A3"].alignment = Alignment(horizontal="center", vertical="center")
            sheet["A3"] = "Gross Trial Balance for the period from %s to %s" % (
                datetime.strptime(str(startdate), "%Y-%m-%d").strftime("%d-%m-%Y"),
                datetime.strptime(str(calculateto), "%Y-%m-%d").strftime("%d-%m-%Y"),
            )
            sheet["A4"] = "Sr. No. "
            sheet["B4"] = "Account Name"
            sheet["C4"] = "Debit"
            sheet["D4"] = "Credit"
            sheet["E4"] = "Dr Balance"
            sheet["F4"] = "Cr Balance"
            sheet["G4"] = "Group Name"
            titlerow = sheet.row_dimensions[4]
            titlerow.font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["C4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["D4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["E4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["F4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["G4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["c4"].alignment = Alignment(horizontal="right")
            sheet["D4"].alignment = Alignment(horizontal="right")
            sheet["E4"].alignment = Alignment(horizontal="right")
            sheet["F4"].alignment = Alignment(horizontal="right")
            sheet["G4"].alignment = Alignment(horizontal="center")
            row = 5
            for record in records:
                sheet["A" + str(row)] = record["srno"]
                sheet["A" + str(row)].alignment = Alignment(horizontal="center")
                sheet["A" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
                sheet["B" + str(row)] = record["accountname"]
                sheet["B" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
                # if record["totaldr"] != "":
                #     sheet["C" + str(row)] = float("%.2f" % float(record["totaldr"]))
                #     sheet["C" + str(row)].number_format = "0.00"
                # sheet["C" + str(row)].alignment = Alignment(horizontal="right")
                # sheet["C" + str(row)].font = Font(name="Liberation Serif", bold=False)
                # if record["totalcr"] != "":
                #     sheet["D" + str(row)] = float("%.2f" % float(record["totalcr"]))
                #     sheet["D" + str(row)].number_format = "0.00"
                # sheet["D" + str(row)].alignment = Alignment(horizontal="right")
                # sheet["D" + str(row)].font = Font(name="Liberation Serif", bold=False)

                # if record["advflag"] == 1:
                #     if record["curbaldr"] != "":
                #         sheet["E" + str(row)] = float(
                #             "%.2f" % float(record["curbaldr"])
                #         )
                #         sheet["E" + str(row)].number_format = "0.00"
                #     sheet["E" + str(row)].alignment = Alignment(horizontal="right")
                #     sheet["E" + str(row)].font = Font(
                #         name="Liberation Serif", size="12", bold=True, color=RED
                #     )
                #     if record["curbalcr"] != "":
                #         sheet["F" + str(row)] = float(
                #             "%.2f" % float(record["curbalcr"])
                #         )
                #         sheet["F" + str(row)].number_format = "0.00"
                #     sheet["F" + str(row)].alignment = Alignment(horizontal="right")
                #     sheet["F" + str(row)].font = Font(
                #         name="Liberation Serif", size="12", bold=True, color=RED
                #     )

                # else:
                #     if record["curbaldr"] != "":
                #         sheet["E" + str(row)] = float(
                #             "%.2f" % float(record["curbaldr"])
                #         )
                #         sheet["E" + str(row)].number_format = "0.00"
                #     sheet["E" + str(row)].alignment = Alignment(horizontal="right")
                #     sheet["E" + str(row)].font = Font(
                #         name="Liberation Serif", size="12", bold=False
                #     )
                #     if record["curbalcr"] != "":
                #         sheet["F" + str(row)] = float(
                #             "%.2f" % float(record["curbalcr"])
                #         )
                #         sheet["F" + str(row)].number_format = "0.00"
                #     sheet["F" + str(row)].alignment = Alignment(horizontal="right")
                #     sheet["F" + str(row)].font = Font(
                #         name="Liberation Serif", size="12", bold=False
                #     )
                sheet["G" + str(row)] = record["groupname"]
                sheet["G" + str(row)].alignment = Alignment(horizontal="center")
                sheet["G" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
                row = row + 1
        # Condition for Extended Trial Balance
        elif trialbalancetype == 3:
            sheet.column_dimensions["A"].width = 8
            sheet.column_dimensions["B"].width = 20
            sheet.column_dimensions["C"].width = 18
            sheet.column_dimensions["D"].width = 16
            sheet.column_dimensions["E"].width = 16
            sheet.column_dimensions["F"].width = 16
            sheet.column_dimensions["G"].width = 16
            sheet.column_dimensions["H"].width = 20
            # Cells of first two rows are merged to display organisation details properly.
            sheet.merge_cells("A1:H2")
            # Name and Financial Year of organisation is fetched to be displayed on the first row.
            sheet["A1"].font = Font(name="Liberation Serif", size="16", bold=True)
            sheet["A1"].alignment = Alignment(horizontal="center", vertical="center")
            # Organisation name and financial year are displayed.
            sheet["A1"] = (
                orgname
                + " (FY: "
                + datetime.strptime(str(financialstart), "%Y-%m-%d").strftime(
                    "%d-%m-%Y"
                )
                + " to "
                + fyend
                + ")"
            )
            sheet.merge_cells("A3:H3")
            sheet["A3"].font = Font(name="Liberation Serif", size="14", bold=True)
            sheet["A3"].alignment = Alignment(horizontal="center", vertical="center")
            sheet["A3"] = "Extended Trial Balance for the period from %s to %s" % (
                datetime.strptime(str(startdate), "%Y-%m-%d").strftime("%d-%m-%Y"),
                datetime.strptime(str(calculateto), "%Y-%m-%d").strftime("%d-%m-%Y"),
            )
            sheet["A4"] = "Sr. No. "
            sheet["B4"] = "Account Name"
            sheet["C4"] = "Opening Balance"
            sheet["D4"] = "Total Debit"
            sheet["E4"] = "Total Credit"
            sheet["F4"] = "Debit Balance"
            sheet["G4"] = "Credit Balance"
            sheet["H4"] = "Group Name"
            titlerow = sheet.row_dimensions[4]
            titlerow.font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["C4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["D4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["E4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["F4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["G4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["H4"].font = Font(name="Liberation Serif", size=12, bold=True)
            sheet["c4"].alignment = Alignment(horizontal="right")
            sheet["D4"].alignment = Alignment(horizontal="right")
            sheet["E4"].alignment = Alignment(horizontal="right")
            sheet["F4"].alignment = Alignment(horizontal="right")
            sheet["G4"].alignment = Alignment(horizontal="right")
            sheet["H4"].alignment = Alignment(horizontal="center")
            row = 5
            for record in records:
                sheet["A" + str(row)] = record["srno"]
                sheet["A" + str(row)].alignment = Alignment(horizontal="center")
                sheet["A" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
                sheet["B" + str(row)] = record["accountname"]
                sheet["B" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
                if record["openingbalance"] == "0.00":
                    sheet["C" + str(row)] = float(
                        "%.2f" % float(record["openingbalance"])
                    )
                    sheet["C" + str(row)].number_format = "0.00"
                    sheet["C" + str(row)].alignment = Alignment(horizontal="right")
                    sheet["C" + str(row)].font = Font(
                        name="Liberation Serif", size="12", bold=False
                    )
                else:
                    sheet["C" + str(row)] = record["openingbalance"]
                    sheet["C" + str(row)].alignment = Alignment(horizontal="right")
                    sheet["C" + str(row)].font = Font(
                        name="Liberation Serif", size="12", bold=False
                    )
                if record["totaldr"] != "":
                    sheet["D" + str(row)] = float("%.2f" % float(record["totaldr"]))
                    sheet["D" + str(row)].number_format = "0.00"
                    sheet["D" + str(row)].alignment = Alignment(horizontal="right")
                    sheet["D" + str(row)].font = Font(
                        name="Liberation Serif", size="12", bold=False
                    )
                if record["totalcr"] != "":
                    sheet["E" + str(row)] = float("%.2f" % float(record["totalcr"]))
                    sheet["E" + str(row)].number_format = "0.00"
                    sheet["E" + str(row)].alignment = Alignment(horizontal="right")
                    sheet["E" + str(row)].font = Font(
                        name="Liberation Serif", size="12", bold=False
                    )
                if record["advflag"] == 1:
                    if record["curbaldr"] != "":
                        sheet["F" + str(row)] = float(
                            "%.2f" % float(record["curbaldr"])
                        )
                        sheet["F" + str(row)].number_format = "0.00"
                        sheet["F" + str(row)].alignment = Alignment(horizontal="right")
                        sheet["F" + str(row)].font = Font(
                            name="Liberation Serif", size="12", bold=True, color=RED
                        )
                    if record["curbalcr"] != "":
                        sheet["G" + str(row)] = float(
                            "%.2f" % float(record["curbalcr"])
                        )
                        sheet["G" + str(row)].number_format = "0.00"
                        sheet["G" + str(row)].alignment = Alignment(horizontal="right")
                        sheet["G" + str(row)].font = Font(
                            name="Liberation Serif", size="12", bold=True, color=RED
                        )
                else:
                    if record["curbaldr"] != "":
                        sheet["F" + str(row)] = float(
                            "%.2f" % float(record["curbaldr"])
                        )
                        sheet["F" + str(row)].number_format = "0.00"
                    sheet["F" + str(row)].alignment = Alignment(horizontal="right")
                    sheet["F" + str(row)].font = Font(
                        name="Liberation Serif", size="12", bold=False
                    )
                    if record["curbalcr"] != "":
                        sheet["G" + str(row)] = float(
                            "%.2f" % float(record["curbalcr"])
                        )
                        sheet["G" + str(row)].number_format = "0.00"
                    sheet["G" + str(row)].alignment = Alignment(horizontal="right")
                    sheet["G" + str(row)].font = Font(
                        name="Liberation Serif", size="12", bold=False
                    )
                sheet["H" + str(row)] = record["groupname"]
                sheet["H" + str(row)].alignment = Alignment(horizontal="center")
                sheet["H" + str(row)].font = Font(
                    name="Liberation Serif", size="12", bold=False
                )
                row = row + 1
        output = io.BytesIO()
        trialbalancewb.save(output)
        contents = output.getvalue()
        output.close()
        headerList = {
            "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "Content-Length": len(contents),
            "Content-Disposition": "attachment; filename=report.xlsx",
            "X-Content-Type-Options": "nosniff",
            "Set-Cookie": "fileDownload=true; path=/ [;HttpOnly]",
        }
        # headerList = {'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' ,'Content-Length': len(contents),'Content-Disposition': 'attachment; filename=report.xlsx','Set-Cookie':'fileDownload=true; path=/'}

        return Response(contents, headerlist=list(headerList.items()))
    except Exception as e:
        print(e)
        return {"gkstatus": 3}
