# generated by datamodel-codegen:
#   filename:  GSTR1 - Save GSTR1 data request_schema_v3.0.json
#   timestamp: 2025-03-06T07:53:25+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class InvTyp(Enum):
    R = 'R'
    DE = 'DE'
    SEWP = 'SEWP'
    SEWOP = 'SEWOP'
    CBW = 'CBW'


class Flag1(Enum):
    D = 'D'


class Flag2(Enum):
    A = 'A'
    R = 'R'


class Flag3(Enum):
    D = 'D'


class Flag4(Enum):
    A = 'A'
    R = 'R'


class Flag5(Enum):
    D = 'D'


class Typ(Enum):
    E = 'E'
    OE = 'OE'


class SplyTy(Enum):
    INTER = 'INTER'
    INTRA = 'INTRA'


class Flag10(Enum):
    A = 'A'
    R = 'R'


class Flag11(Enum):
    D = 'D'


class Flag12(Enum):
    A = 'A'
    R = 'R'


class Typ4(Enum):
    B2CL = 'B2CL'
    EXPWP = 'EXPWP'
    EXPWOP = 'EXPWOP'
    B2CL_1 = 'B2CL'


class Typ5(Enum):
    B2CL = 'B2CL'
    EXPWP = 'EXPWP'
    EXPWOP = 'EXPWOP'
    B2CL_1 = 'B2CL'
    EXPWP_1 = 'EXPWP'
    EXPWOP_1 = 'EXPWOP'


class Typ6(Enum):
    B2CL = 'B2CL'
    EXPWP = 'EXPWP'
    EXPWOP = 'EXPWOP'


class Flag13(Enum):
    D = 'D'


class Typ7(Enum):
    B2CL = 'B2CL'
    EXPWP = 'EXPWP'
    EXPWOP = 'EXPWOP'
    B2CL_1 = 'B2CL'


class Typ8(Enum):
    B2CL = 'B2CL'
    EXPWP = 'EXPWP'
    EXPWOP = 'EXPWOP'
    B2CL_1 = 'B2CL'
    EXPWP_1 = 'EXPWP'
    EXPWOP_1 = 'EXPWOP'


class Typ9(Enum):
    B2CL = 'B2CL'
    EXPWP = 'EXPWP'
    EXPWOP = 'EXPWOP'


class SplyTy4(Enum):
    INTRB2B = 'INTRB2B'
    INTRB2C = 'INTRB2C'
    INTRAB2B = 'INTRAB2B'
    INTRAB2C = 'INTRAB2C'


class ExpTyp(Enum):
    WOPAY = 'WOPAY'
    WPAY = 'WPAY'


class Sbnum(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Shipping Bill No. or Bill of Export No.',
            max_length=7,
            min_length=3,
            pattern='^[0-9]{3,7}$',
        ),
    ]


class Sbnum1(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Shipping Bill No. or Bill of Export No.',
            max_length=0,
            min_length=0,
        ),
    ]


class Sbnum2(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Shipping Bill No. or Bill of Export No.',
            max_length=7,
            min_length=3,
            pattern='^[0-9]{3,7}$',
        ),
    ]


class Sbnum3(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Shipping Bill No. or Bill of Export No.',
            max_length=0,
            min_length=0,
        ),
    ]


class Sbnum4(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Shipping Bill No. or Bill of Export No.',
            max_length=7,
            min_length=3,
            pattern='^[0-9]{3,7}$',
        ),
    ]


class Sbnum5(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Shipping Bill No. or Bill of Export No.',
            max_length=0,
            min_length=0,
        ),
    ]


class Sbnum6(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Shipping Bill No. or Bill of Export No.',
            max_length=7,
            min_length=3,
            pattern='^[0-9]{3,7}$',
        ),
    ]


class Sbnum7(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Shipping Bill No. or Bill of Export No.',
            max_length=0,
            min_length=0,
        ),
    ]


class SplyTy6(Enum):
    INTER = 'INTER'
    INTRA = 'INTRA'


class HsnSc(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='HSN or SAC of Goods or Services as per Invoice line items',
            max_length=8,
            min_length=2,
            pattern='^[0-9]{2,8}$',
        ),
    ]


class HsnSc1(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='HSN or SAC of Goods or Services as per Invoice line items',
            max_length=0,
            min_length=0,
        ),
    ]


class Rt(Enum):
    number_0 = 0
    number_0_1 = 0.1
    number_0_25 = 0.25
    number_1 = 1
    number_1_5 = 1.5
    number_3 = 3
    number_5 = 5
    number_7_5 = 7.5
    number_12 = 12
    number_18 = 18
    number_28 = 28


class NonEmptyString(RootModel[str]):
    root: Annotated[str, Field(min_length=1, pattern='^[a-zA-Z0-9]*$')]


class NonEmptyCost(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, le=99999999999.99, multiple_of=0.01)]


class Txval(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, le=99999999999.99, multiple_of=0.01)]


class Txvalue(RootModel[float]):
    root: Annotated[float, Field(le=99999999999.99, multiple_of=0.01)]


class NonEmptyNil(RootModel[float]):
    root: Annotated[float, Field(le=99999999999.99, multiple_of=0.01)]


class NonEmptyRate(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, le=999.9, multiple_of=0.01)]


class TotalValue(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, le=9999999999999.99, multiple_of=0.01)]


class Hsnamt(RootModel[float]):
    root: Annotated[
        float, Field(ge=-9999999999999.99, le=9999999999999.99, multiple_of=0.01)
    ]


class Hsnqty(RootModel[float]):
    root: Annotated[
        float, Field(ge=-1000000000000000.0, le=1000000000000000.0, multiple_of=0.01)
    ]


class NonEmptydate(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str,
        Field(
            min_length=1,
            pattern='^(0[1-9]|1[0-9]|2[0-8]|29((?=-([0][13-9]|1[0-2])|(?=-(0[1-9]|1[0-2])-([0-9]{2}(0[48]|[13579][26]|[2468][048])|([02468][048]|[13579][26])00))))|30(?=-(0[13-9]|1[0-2]))|31(?=-(0[13578]|1[02])))-(0[1-9]|1[0-2])-[0-9]{4}$',
        ),
    ]


class Gstin(RootModel[str]):
    root: Annotated[
        str,
        Field(
            max_length=15,
            min_length=15,
            pattern='[0-9]{2}[a-zA-Z]{5}[0-9]{4}[a-zA-Z]{1}[1-9A-Za-z]{1}[Zz1-9A-Ja-j]{1}[0-9a-zA-Z]{1}',
        ),
    ]


class Ctin1(RootModel[str]):
    root: Annotated[
        str,
        Field(
            max_length=15,
            min_length=15,
            pattern='[0-9]{2}[a-zA-Z]{5}[0-9]{4}[a-zA-Z]{1}[1-9A-Za-z]{1}[Zz1-9A-Ja-j]{1}[0-9a-zA-Z]{1}',
        ),
    ]


class Ctin2(RootModel[str]):
    root: Annotated[
        str,
        Field(
            max_length=15,
            min_length=15,
            pattern='[0-9]{4}[A-Z]{3}[0-9]{5}[UO]{1}[N][A-Z0-9]{1}',
        ),
    ]


class Ctin3(RootModel[str]):
    root: Annotated[
        str,
        Field(
            max_length=15,
            min_length=15,
            pattern='[0-9]{4}[a-zA-Z]{3}[0-9]{5}[N][R][0-9a-zA-Z]{1}',
        ),
    ]


class Ctin4(RootModel[str]):
    root: Annotated[
        str,
        Field(
            max_length=15,
            min_length=15,
            pattern='[0-9]{2}[a-zA-Z]{4}[a-zA-Z0-9]{1}[0-9]{4}[a-zA-Z]{1}[1-9A-Za-z]{1}[D]{1}[0-9a-zA-Z]{1}',
        ),
    ]


class Ctin(RootModel[Union[Ctin1, Ctin2, Ctin3, Ctin4]]):
    root: Union[Ctin1, Ctin2, Ctin3, Ctin4]


class Etin(RootModel[str]):
    root: Annotated[
        str,
        Field(
            max_length=15,
            min_length=15,
            pattern='[0-9]{2}[a-zA-Z]{5}[0-9]{4}[a-zA-Z]{1}[1-9A-Za-z]{1}[C]{1}[0-9a-zA-Z]{1}',
        ),
    ]


class EtinEmptyChck(RootModel[str]):
    root: Annotated[str, Field(max_length=0, min_length=0)]


class Chksum(RootModel[str]):
    root: Annotated[str, Field(min_length=1, pattern='^[a-zA-Z0-9]+$')]


class Inum(RootModel[str]):
    root: Annotated[str, Field(max_length=16, min_length=1, pattern='^[a-zA-Z0-9-/]+$')]


class StateCd(RootModel[str]):
    root: Annotated[
        str, Field(max_length=2, min_length=2, pattern='^(3[0-8]|[12][0-9]|0[1-9]|97)$')
    ]


class StateCdForeign(RootModel[str]):
    root: Annotated[
        str,
        Field(max_length=2, min_length=2, pattern='^(3[0-8]|[12][0-9]|0[1-9]|96|97)$'),
    ]


class Sbpcode(RootModel[str]):
    root: Annotated[str, Field(max_length=6, min_length=1, pattern='^[a-zA-Z0-9]+$')]


class Flag(Enum):
    N = 'N'
    M = 'M'
    U = 'U'


class Ntty(Enum):
    C = 'C'
    D = 'D'
    R = 'R'


class HsnSupplyTyp(Enum):
    INTRB2B = 'INTRB2B'
    INTRAB2B = 'INTRAB2B'
    INTRB2CL = 'INTRB2CL'
    INTRAB2CL = 'INTRAB2CL'


class Status(Enum):
    A = 'A'
    R = 'R'
    P = 'P'
    N = 'N'
    S = 'S'


class NonEmptyCostAT(RootModel[float]):
    root: Annotated[
        float, Field(ge=-99999999999.99, le=99999999999.99, multiple_of=0.01)
    ]


class Boolean(Enum):
    Y = 'Y'
    N = 'N'


class DocNum(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=12)]


class ItmDet(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    txval: Annotated[
        Txval, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    rt: Annotated[float, Field(description='rate', ge=0.0, le=999.99, multiple_of=0.01)]
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[NonEmptyCost], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyCost], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: Annotated[int, Field(description='Serial no', ge=1)]
    itm_det: ItmDet


class Inv(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    inum: Annotated[Inum, Field(description='Supplier Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Supplier Invoice Date')]
    val: Annotated[TotalValue, Field(description='Supplier Invoice Value')]
    pos: Annotated[
        StateCdForeign,
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    rchrg: Annotated[Boolean, Field(description='Reverse Charge')]
    inv_typ: Annotated[InvTyp, Field(description='tax payer action')]
    itms: Annotated[List[Itm], Field(min_length=1)]


class ItmDet1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    txval: Annotated[
        Optional[Txval],
        Field(description='Taxable value of Goods or Service as per invoice'),
    ] = None
    rt: Annotated[
        Optional[float], Field(description='rate', ge=0.0, le=999.99, multiple_of=0.01)
    ] = None
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[NonEmptyCost], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyCost], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: Annotated[Optional[int], Field(description='Serial no', ge=1)] = None
    itm_det: Optional[ItmDet1] = None


class Inv1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Flag1, Field(description='tax payer action')]
    inum: Annotated[Inum, Field(description='Supplier Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Supplier Invoice Date')]
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    pos: Annotated[
        Optional[StateCdForeign],
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ] = None
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    rchrg: Annotated[Optional[Boolean], Field(description='Reverse Charge')] = None
    inv_typ: Annotated[Optional[InvTyp], Field(description='tax payer action')] = None
    itms: Optional[List[Itm1]] = None


class Itm2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: Annotated[Optional[int], Field(description='Serial no', ge=1)] = None
    itm_det: Optional[ItmDet1] = None


class Inv2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    chksum: Annotated[Chksum, Field(description='Checksum Value')]
    flag: Annotated[Flag2, Field(description='tax payer action')]
    inum: Annotated[Inum, Field(description='Supplier Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Supplier Invoice Date')]
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    pos: Annotated[
        Optional[StateCdForeign],
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ] = None
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    rchrg: Annotated[Optional[Boolean], Field(description='Reverse Charge')] = None
    inv_typ: Annotated[Optional[InvTyp], Field(description='tax payer action')] = None
    itms: Optional[List[Itm2]] = None


class B2bItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ctin: Annotated[
        Ctin, Field(description='GSTIN/UID of the Receiver taxpayer/UN,Govt Bodies')
    ]
    inv: Annotated[List[Union[Inv, Inv1, Inv2]], Field(min_length=1)]


class ItmDet3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    txval: Annotated[
        Txval, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    rt: Annotated[float, Field(description='rate', multiple_of=0.01)]
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[NonEmptyCost], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyCost], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: Annotated[int, Field(description='Serial no', ge=1)]
    itm_det: ItmDet3


class Inv3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    inum: Annotated[Inum, Field(description='Supplier Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Supplier Invoice Date')]
    oinum: Annotated[Inum, Field(description='Supplier Invoice Number')]
    oidt: Annotated[NonEmptydate, Field(description='Supplier Invoice Date')]
    val: Annotated[TotalValue, Field(description='Supplier Invoice Value')]
    pos: Annotated[
        StateCdForeign,
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    rchrg: Annotated[Boolean, Field(description='Reverse Charge')]
    inv_typ: Annotated[InvTyp, Field(description='tax payer action')]
    itms: Annotated[List[Itm3], Field(min_length=1)]


class ItmDet4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    txval: Annotated[
        Optional[Txval],
        Field(description='Taxable value of Goods or Service as per invoice'),
    ] = None
    rt: Annotated[Optional[float], Field(description='rate', multiple_of=0.01)] = None
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[NonEmptyCost], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyCost], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: Annotated[Optional[int], Field(description='Serial no', ge=1)] = None
    itm_det: Optional[ItmDet4] = None


class Inv4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Flag3, Field(description='tax payer action')]
    inum: Annotated[Inum, Field(description='Supplier Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Supplier Invoice Date')]
    oinum: Annotated[Optional[Inum], Field(description='Supplier Invoice Number')] = (
        None
    )
    oidt: Annotated[
        Optional[NonEmptydate], Field(description='Supplier Invoice Date')
    ] = None
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    pos: Annotated[
        Optional[StateCdForeign],
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ] = None
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    rchrg: Annotated[Optional[Boolean], Field(description='Reverse Charge')] = None
    inv_typ: Annotated[Optional[InvTyp], Field(description='tax payer action')] = None
    itms: Optional[List[Itm4]] = None


class Itm5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: Annotated[Optional[int], Field(description='Serial no', ge=1)] = None
    itm_det: Optional[ItmDet4] = None


class Inv5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    chksum: Annotated[Chksum, Field(description='Checksum Value')]
    flag: Annotated[Flag4, Field(description='tax payer action')]
    inum: Annotated[Inum, Field(description='Supplier Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Supplier Invoice Date')]
    oinum: Annotated[Optional[Inum], Field(description='Supplier Invoice Number')] = (
        None
    )
    oidt: Annotated[
        Optional[NonEmptydate], Field(description='Supplier Invoice Date')
    ] = None
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    pos: Annotated[
        Optional[StateCdForeign],
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ] = None
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    rchrg: Annotated[Optional[Boolean], Field(description='Reverse Charge')] = None
    inv_typ: Annotated[Optional[InvTyp], Field(description='tax payer action')] = None
    itms: Optional[List[Itm5]] = None


class B2baItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ctin: Annotated[
        Ctin, Field(description='GSTIN/UID of the Receiver taxpayer/UN,Govt Bodies')
    ]
    inv: Annotated[List[Union[Inv3, Inv4, Inv5]], Field(min_length=1)]


class ItmDet6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rt: Annotated[float, Field(description='rate', ge=0.0, le=999.99, multiple_of=0.01)]
    txval: Annotated[
        Txval, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: Annotated[int, Field(description='Serial no', ge=1)]
    itm_det: ItmDet6


class Inv6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    inum: Annotated[Inum, Field(description='Supplier Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Supplier Invoice Date')]
    val: Annotated[TotalValue, Field(description='Supplier Invoice Value')]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[List[Itm6], Field(min_length=1)]


class ItmDet7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rt: Annotated[
        Optional[float], Field(description='rate', ge=0.0, le=999.99, multiple_of=0.01)
    ] = None
    txval: Annotated[
        Optional[Txval],
        Field(description='Taxable value of Goods or Service as per invoice'),
    ] = None
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: Annotated[Optional[int], Field(description='Serial no', ge=1)] = None
    itm_det: Optional[ItmDet7] = None


class Inv7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Flag5, Field(description='tax payer action')]
    inum: Annotated[Inum, Field(description='Supplier Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Supplier Invoice Date')]
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    pos: Annotated[
        Optional[StateCd],
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service'
        ),
    ] = None
    itms: Optional[List[Itm7]] = None


class B2clItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pos: Annotated[
        StateCd,
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service'
        ),
    ]
    inv: Annotated[List[Union[Inv6, Inv7]], Field(min_length=1)]


class ItmDet8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rt: Annotated[float, Field(description='rate', multiple_of=0.01)]
    txval: Annotated[
        Txval, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: Annotated[int, Field(description='Serial no', ge=1)]
    itm_det: ItmDet8


class Inv8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    inum: Annotated[Inum, Field(description='Supplier Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Supplier Invoice Date')]
    oinum: Annotated[Inum, Field(description='Supplier Invoice Number')]
    oidt: Annotated[NonEmptydate, Field(description='Supplier Invoice Date')]
    val: Annotated[TotalValue, Field(description='Supplier Invoice Value')]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[List[Itm8], Field(min_length=1)]


class ItmDet9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rt: Annotated[Optional[float], Field(description='rate', multiple_of=0.01)] = None
    txval: Annotated[
        Optional[Txval],
        Field(description='Taxable value of Goods or Service as per invoice'),
    ] = None
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm9(BaseModel):
    num: Annotated[Optional[int], Field(description='Serial no', ge=1)] = None
    itm_det: Optional[ItmDet9] = None


class Inv9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Flag5, Field(description='tax payer action')]
    inum: Annotated[Inum, Field(description='Supplier Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Supplier Invoice Date')]
    oinum: Annotated[Optional[Inum], Field(description='Supplier Invoice Number')] = (
        None
    )
    oidt: Annotated[
        Optional[NonEmptydate], Field(description='Supplier Invoice Date')
    ] = None
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    pos: Annotated[
        Optional[StateCd],
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service'
        ),
    ] = None
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Optional[List[Itm9]] = None


class B2claItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pos: Annotated[
        StateCd,
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service'
        ),
    ]
    inv: Annotated[List[Union[Inv8, Inv9]], Field(min_length=1)]


class B2cs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    typ: Annotated[Typ, Field(description='Type of B2cs')]
    sply_ty: Annotated[SplyTy, Field(description='Supply Type of B2cs')]
    rt: Annotated[float, Field(description='rate', ge=0.0, le=999.99, multiple_of=0.01)]
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    pos: Annotated[StateCd, Field(description='Recipient state code')]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    txval: Annotated[
        Txvalue, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    iamt: Annotated[
        Optional[NonEmptyNil], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[NonEmptyNil], Field(description='CGST Rate as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyNil], Field(description='SGST Rate as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyNil], Field(description='Cess Amount as per invoice')
    ] = None


class B2cs1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    typ: Annotated[Typ, Field(description='Type of B2cs')]
    sply_ty: Annotated[SplyTy, Field(description='Supply Type of B2cs')]
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Flag5, Field(description='tax payer action')]
    rt: Annotated[
        Optional[float], Field(description='rate', ge=0.0, le=999.99, multiple_of=0.01)
    ] = None
    pos: Annotated[Optional[StateCd], Field(description='Recipient state code')] = None
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    txval: Annotated[
        Optional[Txvalue],
        Field(description='Taxable value of Goods or Service as per invoice'),
    ] = None
    camt: Annotated[
        Optional[NonEmptyNil], Field(description='CGST Rate as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyNil], Field(description='SGST Rate as per invoice')
    ] = None
    iamt: Annotated[
        Optional[NonEmptyNil], Field(description='IGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyNil], Field(description='Cess Amount as per invoice')
    ] = None


class Itm10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rt: Annotated[float, Field(description='rate', multiple_of=0.01)]
    txval: Annotated[
        Txvalue, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    iamt: Annotated[
        Optional[NonEmptyNil], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[NonEmptyNil], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyNil], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyNil], Field(description='Cess Amount as per invoice')
    ] = None


class B2csa(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    typ: Annotated[Typ, Field(description='Type of B2cs')]
    sply_ty: Annotated[SplyTy, Field(description='Supply Type of B2cs')]
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    pos: Annotated[StateCd, Field(description='Recipient state code')]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    omon: Annotated[
        str,
        Field(
            description='Original Month',
            min_length=1,
            pattern='^((0[1-9]|1[012])((19|20)\\d\\d))$',
        ),
    ]
    itms: Annotated[Optional[List[Itm10]], Field(min_length=1)] = None


class Itm11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rt: Annotated[Optional[float], Field(description='rate', multiple_of=0.01)] = None
    txval: Annotated[
        Optional[Txvalue],
        Field(description='Taxable value of Goods or Service as per invoice'),
    ] = None
    iamt: Annotated[
        Optional[NonEmptyNil], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[NonEmptyNil], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyNil], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyNil], Field(description='Cess Amount as per invoice')
    ] = None


class B2csa1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    typ: Annotated[Typ, Field(description='Type of B2cs')]
    sply_ty: Annotated[SplyTy, Field(description='Supply Type of B2cs')]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    omon: Annotated[
        str,
        Field(
            description='Original Month',
            min_length=1,
            pattern='^((0[1-9]|1[012])((19|20)\\d\\d))$',
        ),
    ]
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Flag5, Field(description='tax payer action')]
    pos: Annotated[StateCd, Field(description='Recipient state code')]
    itms: Optional[List[Itm11]] = None


class ItmDet10(BaseModel):
    txval: Annotated[
        Txval, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    rt: Annotated[float, Field(description='rate', multiple_of=0.01)]
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[NonEmptyCost], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyCost], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm12(BaseModel):
    num: Annotated[int, Field(description='Serial no', ge=1)]
    itm_det: ItmDet10


class Nt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    val: Annotated[TotalValue, Field(description='Supplier Invoice Value')]
    ntty: Annotated[Ntty, Field(description='Credit/debit note type')]
    nt_num: Inum
    nt_dt: NonEmptydate
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    pos: Annotated[
        StateCdForeign,
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ]
    rchrg: Annotated[Boolean, Field(description='Reverse Charge')]
    inv_typ: Annotated[InvTyp, Field(description='tax payer action')]
    itms: Annotated[List[Itm12], Field(min_length=1)]


class ItmDet11(BaseModel):
    txval: Annotated[
        Optional[Txval],
        Field(description='Taxable value of Goods or Service as per invoice'),
    ] = None
    rt: Annotated[Optional[float], Field(description='rate', multiple_of=0.01)] = None
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[NonEmptyCost], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyCost], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm13(BaseModel):
    num: Annotated[Optional[int], Field(description='Serial no', ge=1)] = None
    itm_det: Optional[ItmDet11] = None


class Nt1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Flag5, Field(description='tax payer action')]
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    ntty: Annotated[Optional[Ntty], Field(description='Credit/debit note type')] = None
    nt_num: Inum
    nt_dt: NonEmptydate
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    pos: Annotated[
        Optional[StateCdForeign],
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ] = None
    rchrg: Annotated[Optional[Boolean], Field(description='Reverse Charge')] = None
    inv_typ: Annotated[Optional[InvTyp], Field(description='tax payer action')] = None
    itms: Optional[List[Itm13]] = None


class Itm14(BaseModel):
    num: Annotated[Optional[int], Field(description='Serial no', ge=1)] = None
    itm_det: Optional[ItmDet11] = None


class Nt2(BaseModel):
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    chksum: Annotated[Chksum, Field(description='Checksum Value')]
    flag: Annotated[Flag10, Field(description='tax payer action')]
    pos: Annotated[
        Optional[StateCdForeign],
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ] = None
    rchrg: Annotated[Optional[Boolean], Field(description='Reverse Charge')] = None
    inv_typ: Annotated[Optional[InvTyp], Field(description='tax payer action')] = None
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    ntty: Annotated[Optional[Ntty], Field(description='Credit/debit note type')] = None
    nt_num: Inum
    nt_dt: NonEmptydate
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Optional[List[Itm14]] = None


class CdnrItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ctin: Annotated[
        Ctin, Field(description='GSTIN/UID of the Receiver taxpayer/UN,Govt Bodies')
    ]
    nt: Annotated[List[Union[Nt, Nt1, Nt2]], Field(min_length=1)]


class ItmDet13(BaseModel):
    txval: Annotated[
        Txval, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    rt: Annotated[float, Field(description='rate', multiple_of=0.01)]
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[NonEmptyCost], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyCost], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm15(BaseModel):
    num: Annotated[int, Field(description='Serial no', ge=1)]
    itm_det: ItmDet13


class Nt3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    pos: Annotated[
        StateCdForeign,
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ]
    rchrg: Annotated[Boolean, Field(description='Reverse Charge')]
    inv_typ: Annotated[InvTyp, Field(description='tax payer action')]
    val: Annotated[TotalValue, Field(description='Supplier Invoice Value')]
    ntty: Annotated[Ntty, Field(description='Credit/debit note type')]
    nt_num: Inum
    nt_dt: NonEmptydate
    ont_num: Inum
    ont_dt: NonEmptydate
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[List[Itm15], Field(min_length=1)]


class ItmDet14(BaseModel):
    txval: Annotated[
        Optional[Txval],
        Field(description='Taxable value of Goods or Service as per invoice'),
    ] = None
    rt: Annotated[Optional[float], Field(description='rate', multiple_of=0.01)] = None
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[NonEmptyCost], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyCost], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm16(BaseModel):
    num: Annotated[Optional[int], Field(description='Serial no', ge=1)] = None
    itm_det: Optional[ItmDet14] = None


class Nt4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    flag: Annotated[Flag11, Field(description='tax payer action')]
    pos: Annotated[
        Optional[StateCdForeign],
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ] = None
    rchrg: Annotated[Optional[Boolean], Field(description='Reverse Charge')] = None
    inv_typ: Annotated[Optional[InvTyp], Field(description='tax payer action')] = None
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    ntty: Annotated[Optional[Ntty], Field(description='Credit/debit note type')] = None
    nt_num: Inum
    nt_dt: NonEmptydate
    ont_num: Optional[Inum] = None
    ont_dt: Optional[NonEmptydate] = None
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Optional[List[Itm16]] = None


class Itm17(BaseModel):
    num: Annotated[Optional[int], Field(description='Serial no', ge=1)] = None
    itm_det: Optional[ItmDet14] = None


class Nt5(BaseModel):
    etin: Annotated[
        Optional[Union[Etin, EtinEmptyChck]], Field(description='Ecom Tin')
    ] = None
    chksum: Annotated[Chksum, Field(description='Checksum Value')]
    flag: Annotated[Flag12, Field(description='tax payer action')]
    pos: Annotated[
        Optional[StateCdForeign],
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ] = None
    rchrg: Annotated[Optional[Boolean], Field(description='Reverse Charge')] = None
    inv_typ: Annotated[Optional[InvTyp], Field(description='tax payer action')] = None
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    ntty: Annotated[Optional[Ntty], Field(description='Credit/debit note type')] = None
    nt_num: Inum
    nt_dt: NonEmptydate
    ont_num: Optional[Inum] = None
    ont_dt: Optional[NonEmptydate] = None
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Optional[List[Itm17]] = None


class CdnraItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ctin: Annotated[
        Ctin, Field(description='GSTIN/UID of the Receiver taxpayer/UN,Govt Bodies')
    ]
    nt: Annotated[List[Union[Nt3, Nt4, Nt5]], Field(min_length=1)]


class ItmDet16(BaseModel):
    txval: Annotated[
        Txval, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    rt: Annotated[float, Field(description='rate', multiple_of=0.01)]
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[NonEmptyCost], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyCost], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm18(BaseModel):
    num: Annotated[int, Field(description='Serial no', ge=0)]
    itm_det: ItmDet16


class Cdnur(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    typ: Annotated[Typ4, Field(description='Typ of invoice')]
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    pos: Annotated[
        StateCd,
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ]
    val: Annotated[TotalValue, Field(description='Supplier Invoice Value')]
    ntty: Annotated[Ntty, Field(description='Credit/debit note type')]
    nt_num: Inum
    nt_dt: NonEmptydate
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[List[Itm18], Field(min_length=1)]


class Itm19(BaseModel):
    num: Annotated[int, Field(description='Serial no', ge=0)]
    itm_det: ItmDet16


class Cdnur1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    typ: Annotated[Typ5, Field(description='Typ of invoice')]
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    pos: Annotated[
        StateCd,
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ]
    val: Annotated[TotalValue, Field(description='Supplier Invoice Value')]
    ntty: Annotated[Ntty, Field(description='Credit/debit note type')]
    nt_num: Inum
    nt_dt: NonEmptydate
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[List[Itm19], Field(min_length=1)]


class ItmDet18(BaseModel):
    txval: Annotated[
        Optional[Txval],
        Field(description='Taxable value of Goods or Service as per invoice'),
    ] = None
    rt: Annotated[Optional[float], Field(description='rate', multiple_of=0.01)] = None
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[NonEmptyCost], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[NonEmptyCost], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm20(BaseModel):
    num: Annotated[Optional[int], Field(description='Serial no', ge=0)] = None
    itm_det: Optional[ItmDet18] = None


class Cdnur2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    typ: Annotated[Typ6, Field(description='Typ of invoice')]
    flag: Annotated[Flag13, Field(description='tax payer action')]
    pos: Annotated[
        Optional[StateCd],
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ] = None
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    ntty: Annotated[Optional[Ntty], Field(description='Credit/debit note type')] = None
    nt_num: Inum
    nt_dt: NonEmptydate
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Optional[List[Itm20]] = None


class ItmDet19(BaseModel):
    txval: Annotated[
        Txval, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    rt: Annotated[float, Field(description='rate', multiple_of=0.01)]
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm21(BaseModel):
    num: Annotated[int, Field(description='Serial no', ge=1)]
    itm_det: ItmDet19


class Cdnura(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    typ: Annotated[Typ7, Field(description='Typ of invoice')]
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    pos: Annotated[
        StateCd,
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ]
    val: Annotated[TotalValue, Field(description='Supplier Invoice Value')]
    ntty: Annotated[Ntty, Field(description='Credit/debit note type')]
    nt_num: Inum
    nt_dt: NonEmptydate
    ont_num: Inum
    ont_dt: NonEmptydate
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[List[Itm21], Field(min_length=1)]


class Itm22(BaseModel):
    num: Annotated[int, Field(description='Serial no', ge=1)]
    itm_det: ItmDet19


class Cdnura1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    typ: Annotated[Typ8, Field(description='Typ of invoice')]
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    pos: Annotated[
        StateCd,
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ]
    val: Annotated[TotalValue, Field(description='Supplier Invoice Value')]
    ntty: Annotated[Ntty, Field(description='Credit/debit note type')]
    nt_num: Inum
    nt_dt: NonEmptydate
    ont_num: Inum
    ont_dt: NonEmptydate
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[List[Itm22], Field(min_length=1)]


class ItmDet21(BaseModel):
    txval: Annotated[
        Optional[Txval],
        Field(description='Taxable value of Goods or Service as per invoice'),
    ] = None
    rt: Annotated[Optional[float], Field(description='rate', multiple_of=0.01)] = None
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Itm23(BaseModel):
    num: Annotated[Optional[int], Field(description='Serial no', ge=1)] = None
    itm_det: Optional[ItmDet21] = None


class Cdnura2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    typ: Annotated[Typ9, Field(description='Typ of invoice')]
    flag: Annotated[Flag13, Field(description='tax payer action')]
    pos: Annotated[
        Optional[StateCd],
        Field(
            description='Maintained in GST System common database POS as provided in law / actual provision of service.'
        ),
    ] = None
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    ntty: Annotated[Optional[Ntty], Field(description='Credit/debit note type')] = None
    nt_num: Inum
    nt_dt: NonEmptydate
    ont_num: Optional[Inum] = None
    ont_dt: Optional[NonEmptydate] = None
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Optional[List[Itm23]] = None


class InvItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sply_ty: Annotated[SplyTy4, Field(description='Supply Type')]
    nil_amt: Annotated[
        NonEmptyNil, Field(description='Total Nil rated outward supplies')
    ]
    expt_amt: Annotated[
        NonEmptyNil, Field(description='Total Exempted outward supplies')
    ]
    ngsup_amt: Annotated[
        NonEmptyNil, Field(description='Total Non GST outward supplies')
    ]


class Nil(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    inv: Annotated[List[InvItem], Field(min_length=1)]


class InvItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sply_ty: Annotated[Optional[SplyTy4], Field(description='Supply Type')] = None
    nil_amt: Annotated[
        Optional[NonEmptyNil], Field(description='Total Nil rated outward supplies')
    ] = None
    expt_amt: Annotated[
        Optional[NonEmptyNil], Field(description='Total Exempted outward supplies')
    ] = None
    ngsup_amt: Annotated[
        Optional[NonEmptyNil], Field(description='Total Non GST outward supplies')
    ] = None


class Nil1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Flag13, Field(description='tax payer action')]
    inv: Optional[List[InvItem1]] = None


class Itm24(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    txval: Annotated[
        Txval, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    rt: Annotated[float, Field(description='rate', ge=0.0, le=999.99, multiple_of=0.01)]
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Inv10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    inum: Annotated[Inum, Field(description='Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Export Invoice date')]
    val: Annotated[TotalValue, Field(description='Supplier Invoice Value')]
    sbnum: Optional[Union[Sbnum, Sbnum1]] = None
    sbdt: Annotated[
        Optional[NonEmptydate],
        Field(description='Shipping Bill Date. or Bill of Export Date'),
    ] = None
    sbpcode: Annotated[Optional[Sbpcode], Field(description='Port Code')] = None
    itms: Annotated[List[Itm24], Field(min_length=1)]


class Itm25(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    txval: Annotated[
        Optional[Txval],
        Field(description='Taxable value of Goods or Service as per invoice'),
    ] = None
    rt: Annotated[
        Optional[float], Field(description='rate', ge=0.0, le=999.99, multiple_of=0.01)
    ] = None
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Inv11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Flag13, Field(description='tax payer action')]
    inum: Annotated[Inum, Field(description='Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Export Invoice date')]
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    sbnum: Optional[Union[Sbnum2, Sbnum3]] = None
    sbdt: Annotated[
        Optional[NonEmptydate],
        Field(description='Shipping Bill Date. or Bill of Export Date'),
    ] = None
    sbpcode: Annotated[Optional[Sbpcode], Field(description='Port Code')] = None
    itms: Optional[List[Itm25]] = None


class ExpItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    exp_typ: Annotated[
        ExpTyp, Field(description='Supplies exported types i.e WithPay,WithoutPay')
    ]
    inv: Annotated[List[Union[Inv10, Inv11]], Field(min_length=1)]


class Itm26(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    txval: Annotated[
        Txval, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    rt: Annotated[NonEmptyCost, Field(description='Rate as per invoice')]
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Inv12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    inum: Annotated[Inum, Field(description='Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Export Invoice date')]
    val: Annotated[TotalValue, Field(description='Supplier Invoice Value')]
    sbnum: Optional[Union[Sbnum4, Sbnum5]] = None
    sbdt: Annotated[
        Optional[NonEmptydate],
        Field(description='Shipping Bill Date. or Bill of Export Date'),
    ] = None
    sbpcode: Annotated[Optional[Sbpcode], Field(description='Port Code')] = None
    oinum: Annotated[Inum, Field(description='Original invoice number')]
    oidt: Annotated[NonEmptydate, Field(description='Original invoice date')]
    itms: Annotated[List[Itm26], Field(min_length=1)]


class Itm27(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    txval: Annotated[
        Optional[Txval],
        Field(description='Taxable value of Goods or Service as per invoice'),
    ] = None
    rt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Rate as per invoice')
    ] = None
    iamt: Annotated[
        Optional[NonEmptyCost], Field(description='IGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[NonEmptyCost], Field(description='Cess Amount as per invoice')
    ] = None


class Inv13(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Flag13, Field(description='tax payer action')]
    inum: Annotated[Inum, Field(description=' Invoice Number')]
    idt: Annotated[NonEmptydate, Field(description='Export Invoice date')]
    val: Annotated[
        Optional[TotalValue], Field(description='Supplier Invoice Value')
    ] = None
    sbnum: Optional[Union[Sbnum6, Sbnum7]] = None
    sbdt: Annotated[
        Optional[NonEmptydate],
        Field(description='Shipping Bill Date. or Bill of Export Date'),
    ] = None
    sbpcode: Annotated[Optional[Sbpcode], Field(description='Port Code')] = None
    oinum: Annotated[Optional[Inum], Field(description='Original invoice number')] = (
        None
    )
    oidt: Annotated[
        Optional[NonEmptydate], Field(description='Original invoice date')
    ] = None
    itms: Optional[List[Itm27]] = None


class ExpaItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    exp_typ: Annotated[
        ExpTyp, Field(description='Supplies exported types i.e WithPay,WithoutPay')
    ]
    inv: Annotated[List[Union[Inv12, Inv13]], Field(min_length=1)]


class Itm28(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ad_amt: Annotated[NonEmptyCostAT, Field(description='Amount of Advance received')]
    csamt: Optional[NonEmptyCostAT] = None
    camt: Optional[NonEmptyCostAT] = None
    samt: Optional[NonEmptyCostAT] = None
    iamt: Optional[NonEmptyCostAT] = None
    rt: Annotated[float, Field(description='rate', ge=0.0, le=999.99, multiple_of=0.01)]


class At(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    pos: Annotated[StateCd, Field(description='Recipient state code')]
    sply_ty: Annotated[SplyTy6, Field(description='Supply Type of invoice')]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[List[Itm28], Field(description='Item Details', min_length=1)]


class Itm29(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ad_amt: Annotated[
        Optional[NonEmptyCostAT], Field(description='Amount of Advance received')
    ] = None
    csamt: Optional[NonEmptyCostAT] = None
    camt: Optional[NonEmptyCostAT] = None
    samt: Optional[NonEmptyCostAT] = None
    iamt: Optional[NonEmptyCostAT] = None
    rt: Annotated[
        Optional[float], Field(description='rate', ge=0.0, le=999.99, multiple_of=0.01)
    ] = None


class At1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Flag13, Field(description='tax payer action')]
    pos: Annotated[Optional[StateCd], Field(description='Recipient state code')] = None
    sply_ty: Annotated[SplyTy6, Field(description='Supply Type of invoice')]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[
        Optional[List[Itm29]], Field(description='Item Details', min_length=1)
    ] = None


class Itm30(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ad_amt: Annotated[NonEmptyCostAT, Field(description='Amount of Advance received')]
    csamt: Optional[NonEmptyCostAT] = None
    camt: Optional[NonEmptyCostAT] = None
    samt: Optional[NonEmptyCostAT] = None
    iamt: Optional[NonEmptyCostAT] = None
    rt: NonEmptyRate


class Ata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    pos: Annotated[StateCd, Field(description='Recipient state code')]
    omon: Annotated[
        str,
        Field(
            description='Original Month',
            min_length=1,
            pattern='^((0[1-9]|1[012])((19|20)\\d\\d))$',
        ),
    ]
    sply_ty: Annotated[SplyTy6, Field(description='Supply Type of invoice')]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[List[Itm30], Field(description='Item Details', min_length=1)]


class Itm31(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ad_amt: Annotated[
        Optional[NonEmptyCostAT], Field(description='Amount of Advance received')
    ] = None
    csamt: Optional[NonEmptyCostAT] = None
    camt: Optional[NonEmptyCostAT] = None
    samt: Optional[NonEmptyCostAT] = None
    iamt: Optional[NonEmptyCostAT] = None
    rt: Optional[NonEmptyRate] = None


class Ata1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Flag13, Field(description='tax payer action')]
    pos: Annotated[StateCd, Field(description='Recipient state code')]
    omon: Annotated[
        Optional[str],
        Field(
            description='Original Month',
            min_length=1,
            pattern='^((0[1-9]|1[012])((19|20)\\d\\d))$',
        ),
    ] = None
    sply_ty: Annotated[SplyTy6, Field(description='Supply Type of invoice')]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[Optional[List[Itm31]], Field(description='Item Details')] = None


class Itm32(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ad_amt: Annotated[NonEmptyCost, Field(description='Amount of Advance received')]
    csamt: Optional[NonEmptyCost] = None
    camt: Optional[NonEmptyCost] = None
    samt: Optional[NonEmptyCost] = None
    iamt: Optional[NonEmptyCost] = None
    rt: Annotated[float, Field(description='rate', ge=0.0, le=999.99, multiple_of=0.01)]


class Txpd(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    pos: Annotated[StateCd, Field(description='Recipient state code')]
    sply_ty: Annotated[SplyTy6, Field(description='Supply Type of invoice')]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[List[Itm32], Field(description='Item Details', min_length=1)]


class Itm33(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ad_amt: Annotated[
        Optional[NonEmptyCost], Field(description='Amount of Advance received')
    ] = None
    csamt: Optional[NonEmptyCost] = None
    camt: Optional[NonEmptyCost] = None
    samt: Optional[NonEmptyCost] = None
    iamt: Optional[NonEmptyCost] = None
    rt: Annotated[
        Optional[float], Field(description='rate', ge=0.0, le=999.99, multiple_of=0.01)
    ] = None


class Txpd1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Flag13, Field(description='tax payer action')]
    pos: Annotated[Optional[StateCd], Field(description='Recipient state code')] = None
    sply_ty: Annotated[SplyTy6, Field(description='Supply Type of invoice')]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[Optional[List[Itm33]], Field(description='Item Details')] = None


class Itm34(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ad_amt: Annotated[NonEmptyCost, Field(description='Amount of Advance received')]
    csamt: Optional[NonEmptyCost] = None
    camt: Optional[NonEmptyCost] = None
    samt: Optional[NonEmptyCost] = None
    iamt: Optional[NonEmptyCost] = None
    rt: NonEmptyRate


class Txpda(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    pos: Annotated[StateCd, Field(description='Recipient state code')]
    omon: Annotated[
        str,
        Field(
            description='Original Month',
            min_length=1,
            pattern='^((0[1-9]|1[012])((19|20)\\d\\d))$',
        ),
    ]
    sply_ty: Annotated[SplyTy6, Field(description='Supply Type of invoice')]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[List[Itm34], Field(description='Item Details', min_length=1)]


class Itm35(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ad_amt: Annotated[
        Optional[NonEmptyCost], Field(description='Amount of Advance received')
    ] = None
    csamt: Optional[NonEmptyCost] = None
    camt: Optional[NonEmptyCost] = None
    samt: Optional[NonEmptyCost] = None
    iamt: Optional[NonEmptyCost] = None
    rt: Optional[NonEmptyRate] = None


class Txpda1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Flag13, Field(description='tax payer action')]
    pos: Annotated[StateCd, Field(description='Recipient state code')]
    omon: Annotated[
        Optional[str],
        Field(
            description='Original Month',
            min_length=1,
            pattern='^((0[1-9]|1[012])((19|20)\\d\\d))$',
        ),
    ] = None
    sply_ty: Annotated[SplyTy6, Field(description='Supply Type of invoice')]
    diff_percent: Annotated[
        Optional[float], Field(description='Differential percentage', multiple_of=0.01)
    ] = None
    itms: Annotated[Optional[List[Itm35]], Field(description='Item Details')] = None


class Data(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: Annotated[int, Field(description='Serial no', ge=1)]
    hsn_sc: Annotated[
        str,
        Field(
            description='HSN or SAC of Goods or Services as per Invoice line items',
            max_length=8,
            min_length=2,
            pattern='^[0-9]{2,8}$',
        ),
    ]
    val: Annotated[
        float,
        Field(
            description='Supplier Invoice Value',
            le=1000000000000000.0,
            multiple_of=0.01,
        ),
    ]
    txval: Annotated[
        Hsnamt, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    iamt: Annotated[
        Optional[Hsnamt], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[Hsnamt], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[Hsnamt], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[Hsnamt], Field(description='Cess Amount as per invoice')
    ] = None
    desc: Annotated[
        Optional[str],
        Field(description='Description of goods sold', max_length=30, min_length=0),
    ] = None
    uqc: Annotated[
        str,
        Field(
            description='UQC (Unit of Measure) of goods sold',
            max_length=30,
            min_length=1,
            pattern='^[a-zA-Z]*$',
        ),
    ]
    qty: Annotated[Hsnqty, Field(description='Quantity of goods sold')]


class Data1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: Annotated[int, Field(description='Serial no', ge=1)]
    hsn_sc: Annotated[Optional[Union[HsnSc, HsnSc1]], Field(description='hsn ')] = None
    val: Annotated[
        float,
        Field(
            description='Supplier Invoice Value',
            le=1000000000000000.0,
            multiple_of=0.01,
        ),
    ]
    txval: Annotated[
        Hsnamt, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    iamt: Annotated[
        Optional[Hsnamt], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[Hsnamt], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[Hsnamt], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[Hsnamt], Field(description='Cess Amount as per invoice')
    ] = None
    desc: Annotated[
        str, Field(description='Description of goods sold', max_length=30, min_length=1)
    ]
    uqc: Annotated[
        str,
        Field(
            description='UQC (Unit of Measure) of goods sold',
            max_length=30,
            min_length=1,
            pattern='^[a-zA-Z]*$',
        ),
    ]
    qty: Annotated[Hsnqty, Field(description='Quantity of goods sold')]


class Data2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: Annotated[int, Field(description='Serial no', ge=1)]
    hsn_sc: Annotated[
        str,
        Field(
            description='HSN or SAC of Goods or Services as per Invoice line items',
            max_length=8,
            min_length=2,
            pattern='^[0-9]{2,8}$',
        ),
    ]
    val: Annotated[
        Optional[float], Field(description='Supplier Invoice Value', ge=0.0, le=0.0)
    ] = None
    txval: Annotated[
        Hsnamt, Field(description='Taxable value of Goods or Service as per invoice')
    ]
    iamt: Annotated[
        Optional[Hsnamt], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[Hsnamt], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[Hsnamt], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[Hsnamt], Field(description='Cess Amount as per invoice')
    ] = None
    desc: Annotated[Optional[str], Field(description='Description of goods sold')] = (
        None
    )
    uqc: Annotated[
        str,
        Field(
            description='UQC (Unit of Measure) of goods sold',
            max_length=30,
            min_length=1,
            pattern='^[a-zA-Z]*$',
        ),
    ]
    qty: Annotated[Hsnqty, Field(description='Quantity of goods sold')]
    rt: Annotated[Rt, Field(description='rate')]


class Hsn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    data: Annotated[List[Union[Data, Data1, Data2]], Field(min_length=1)]


class Datum(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: Annotated[Optional[int], Field(description='Serial no', ge=1)] = None
    hsn_sc: Annotated[
        Optional[str],
        Field(
            description='HSN or SAC of Goods or Services as per Invoice line items',
            max_length=8,
            min_length=2,
            pattern='^[0-9]{2,8}$',
        ),
    ] = None
    val: Annotated[Optional[float], Field(description='Supplier Invoice Value')] = None
    txval: Annotated[
        Optional[Hsnamt],
        Field(description='Taxable value of Goods or Service as per invoice'),
    ] = None
    iamt: Annotated[
        Optional[Hsnamt], Field(description='IGST Amount as per invoice')
    ] = None
    camt: Annotated[
        Optional[Hsnamt], Field(description='CGST Amount as per invoice')
    ] = None
    samt: Annotated[
        Optional[Hsnamt], Field(description='SGST Amount as per invoice')
    ] = None
    csamt: Annotated[
        Optional[Hsnamt], Field(description='Cess Amount as per invoice')
    ] = None
    desc: Annotated[Optional[str], Field(description='Description of goods sold')] = (
        None
    )
    uqc: Annotated[
        Optional[str],
        Field(
            description='UQC (Unit of Measure) of goods sold',
            max_length=30,
            min_length=1,
            pattern='^[a-zA-Z]*$',
        ),
    ] = None
    qty: Annotated[Optional[Hsnqty], Field(description='Quantity of goods sold')] = None
    rt: Annotated[Optional[Rt], Field(description='rate')] = None


class Hsn1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Flag13, Field(description='tax payer action')]
    data: Optional[List[Datum]] = None


class Doc(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cancel: Annotated[int, Field(description='Cancelled Amount', ge=0, le=9999999999)]
    from_: Annotated[Inum, Field(alias='from')]
    net_issue: Annotated[int, Field(ge=0, le=9999999999)]
    num: Annotated[int, Field(description='Serial no', ge=1)]
    to: Inum
    totnum: Annotated[int, Field(description='Total no', ge=0, le=9999999999)]


class DocDetItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    doc_num: Annotated[DocNum, Field(description='Document Number')]
    doc_typ: Annotated[
        Optional[str], Field(description='Nature of document', min_length=1)
    ] = None
    docs: List[Doc]


class DocIssue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Optional[Flag], Field(description='tax payer action')] = None
    doc_det: List[DocDetItem]


class Doc1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cancel: Annotated[
        Optional[int], Field(description='Cancelled Amount', ge=0, le=9999999999)
    ] = None
    from_: Annotated[Optional[Inum], Field(alias='from')] = None
    net_issue: Annotated[Optional[int], Field(ge=0, le=9999999999)] = None
    num: Annotated[Optional[int], Field(description='Serial no', ge=1)] = None
    to: Optional[Inum] = None
    totnum: Annotated[
        Optional[int], Field(description='Total no', ge=0, le=9999999999)
    ] = None


class DocDetItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    doc_num: Annotated[Optional[DocNum], Field(description='Document Number')] = None
    doc_typ: Annotated[
        Optional[str], Field(description='Nature of document', min_length=1)
    ] = None
    docs: Optional[List[Doc1]] = None


class DocIssue1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag: Annotated[Flag13, Field(description='tax payer action')]
    doc_det: Optional[List[DocDetItem1]] = None


class Gstr1SchemaV30(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    gstin: Annotated[Gstin, Field(description='Supplier GSTIN')]
    fp: Annotated[
        str,
        Field(
            description='Financial Period',
            min_length=1,
            pattern='^((0[1-9]|1[012])((19|20)\\d\\d))$',
        ),
    ]
    gt: Annotated[
        Optional[float],
        Field(
            description='Gross Turnover of the taxpayer in the previous FY',
            ge=0.0,
            le=1000000000000000.0,
            multiple_of=0.01,
        ),
    ] = None
    cur_gt: Annotated[
        Optional[float],
        Field(
            description='Gross Turnover of the taxpayer in the previous FY',
            ge=0.0,
            le=1000000000000000.0,
            multiple_of=0.01,
        ),
    ] = None
    hash: Annotated[Optional[str], Field(description='hash')] = None
    version: Annotated[Optional[str], Field(description='version')] = None
    b2b: Optional[List[B2bItem]] = None
    b2ba: Optional[List[B2baItem]] = None
    b2cl: Optional[List[B2clItem]] = None
    b2cla: Optional[List[B2claItem]] = None
    b2cs: Optional[List[Union[B2cs, B2cs1]]] = None
    b2csa: Optional[List[Union[B2csa, B2csa1]]] = None
    cdnr: Optional[List[CdnrItem]] = None
    cdnra: Optional[List[CdnraItem]] = None
    cdnur: Optional[List[Union[Union[Cdnur, Cdnur1], Cdnur2]]] = None
    cdnura: Optional[List[Union[Union[Cdnura, Cdnura1], Cdnura2]]] = None
    nil: Optional[Union[Nil, Nil1]] = None
    exp: Optional[List[ExpItem]] = None
    expa: Optional[List[ExpaItem]] = None
    at: Optional[List[Union[At, At1]]] = None
    ata: Optional[List[Union[Ata, Ata1]]] = None
    txpd: Optional[List[Union[Txpd, Txpd1]]] = None
    txpda: Annotated[Optional[List[Union[Txpda, Txpda1]]], Field(min_length=1)] = None
    hsn: Optional[Union[Hsn, Hsn1]] = None
    doc_issue: Optional[Union[DocIssue, DocIssue1]] = None
